CREATE TABLE [CommonFormat].[SalaryPackageBenefit_Phoenix]
(
[SalaryPackageBenefitId] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SalaryPackageId] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BenefitType] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PaymentMethod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreditorId] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankBSB] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BankAccountNumber] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BankAccountName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TaxType] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerReference] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentStartPayNumber] [int] NULL,
[CurrentNumberOfPays] [int] NULL,
[NextStartPayNumber] [int] NULL,
[NextNumberOfPays] [int] NULL,
[NextFBTAnnualAmount] [decimal] (16, 2) NOT NULL,
[ThisFBTAnnualAmount] [decimal] (16, 2) NOT NULL,
[EffectiveStartDate] [date] NOT NULL,
[EffectiveEndDate] [date] NULL,
[SuperAbn] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PolicyNumber] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GstYear] [decimal] (16, 2) NULL,
[OrganisationSharePercent] [decimal] (16, 2) NULL,
[GrossUp] [decimal] (16, 2) NULL,
[FixedSubstantiationRequired] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubstantiationAmount] [decimal] (16, 2) NULL,
[OutstandingAmount] [decimal] (16, 2) NULL,
[NextNumberOfPaysOffset] [int] NULL,
[BankAccountId] [int] NULL,
[IsPaymentMethodId] [bit] NULL,
[FBTTaxLiability] [bit] NULL,
[IsRecurringSubs] [bit] NULL,
[IsBalance] [bit] NULL,
[FBTBalance] [bit] NULL,
[IsPOE] [bit] NULL,
[POESupportingDocAmt] [bit] NULL,
[POETaxInvoiceHeld] [bit] NULL,
[IsVehicleManagement] [bit] NULL,
[IsDeleted] [bit] NULL CONSTRAINT [DF_SalaryPackageBenefit_Phoenix_IsDeleted] DEFAULT ((0)),
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedDate] [datetime] NOT NULL,
[UpdatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UpdatedDate] [datetime] NOT NULL,
[CreditorId_cf] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextPayAmount] [decimal] (16, 2) NULL,
[P1_CN] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P1_C] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThisFBTpa] [decimal] (16, 2) NULL,
[NextFBTpa] [decimal] (16, 2) NULL,
[ThisFBTpp] [decimal] (16, 2) NULL,
[NextFBTpp] [decimal] (16, 2) NULL,
[WCTitle] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCFirstName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCLastName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCGender] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCDOB] [date] NULL,
[WCOccupationCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCBSB] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCAccountNumber] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCHasSecondaryCard] [bit] NULL,
[WCInfoOrgProcessed] [date] NULL,
[WCTokenNumber] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCCustNumber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCOpenReqToWBC] [datetime] NULL,
[WCOpenConfirmed] [datetime] NULL,
[WCCloseInitiated] [datetime] NULL,
[WCCloseRequested] [datetime] NULL,
[WCCloseConfirmed] [datetime] NULL,
[WCSecondaryTitle] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryFirstName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryLastName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryGender] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryDOB] [date] NULL,
[WCSecondaryOccupationCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryBSB] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryAccountNumber] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryCustNumber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WCSecondaryOpenReqToWBC] [datetime] NULL,
[WCSecondaryOpenConfirmed] [datetime] NULL,
[WCSecondaryCloseInitiated] [datetime] NULL,
[WCSecondaryCloseRequested] [datetime] NULL,
[WCSecondaryCloseConfirmed] [datetime] NULL,
[EPBEndDate] [date] NULL,
[EPBExcludeFromCap] [bit] NULL,
[JSON] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [CommonFormat].[SalaryPackageBenefit_Phoenix] ADD CONSTRAINT [PK_SalaryPackageBenefit] PRIMARY KEY CLUSTERED  ([SalaryPackageBenefitId]) ON [PRIMARY]
GO
